// Reason: Decoupled formatters for transforming base content to IDE-specific formats.

const { getAdapter } = require("./ide-adapters");

/**
 * 将纯内容格式化为 IDE 特定格式
 * @param {string} content - 纯规则内容（无格式）
 * @param {string} ide - IDE 标识符
 * @param {object} meta - 元数据（description, globs, alwaysApply, title）
 * @returns {string} 格式化后的内容
 */
function formatForIde(content, ide, meta = {}) {
  const adapter = getAdapter(ide);
  let formatted = content;

  // 替换 IDE 特定占位符
  if (adapter.placeholders) {
    for (const [placeholder, value] of Object.entries(adapter.placeholders)) {
      formatted = formatted.replace(new RegExp(placeholder, "g"), value);
    }
  }

  // 替换通用占位符
  formatted = formatted.replace(/__IDE_RULES_DIR__/g, adapter.rulesDir);

  // 添加 IDE 特定的头部
  let header = "";
  if (adapter.supportsFrontmatter && adapter.frontmatterTemplate) {
    header = adapter.frontmatterTemplate(meta);
  } else if (adapter.headerTemplate) {
    header = adapter.headerTemplate(meta);
  }

  // 如果内容以 frontmatter 开头（旧格式），先移除
  formatted = stripExistingFrontmatter(formatted);

  // 确保 header 和 content 之间有换行
  if (header && !header.endsWith("\n")) {
    header += "\n";
  }

  return header + formatted;
}

/**
 * 移除内容中已有的 frontmatter
 */
function stripExistingFrontmatter(content) {
  const frontmatterRegex = /^---[\s\S]*?---\n*/;
  return content.replace(frontmatterRegex, "");
}

/**
 * 格式化基础规则文件
 */
function formatBaseRule(content, ide) {
  const meta = {
    description: "基础架构师规则 - 定义工作流、代码标准及自进化协议。",
    globs: "*",
    alwaysApply: true,
    title: "Base Rule"
  };
  return formatForIde(content, ide, meta);
}

/**
 * 格式化分类规则文件（frontend/backend/language）
 */
function formatCategoryRule(content, ide, category, name) {
  const meta = {
    description: `${category} guideline for ${name}`,
    globs: "*",
    alwaysApply: false,
    title: `${category}: ${name}`
  };
  return formatForIde(content, ide, meta);
}

/**
 * 获取规则文件的输出文件名
 */
function getOutputFileName(ide, baseName) {
  const adapter = getAdapter(ide);

  // 如果是单文件 IDE 且有固定文件名
  if (adapter.singleFile && adapter.fileName) {
    return adapter.fileName;
  }

  // 如果是单文件 IDE（如 Windsurf）
  if (adapter.singleFile) {
    return adapter.fileExt.startsWith(".")
      ? adapter.fileExt.substring(1)
      : adapter.fileExt;
  }

  // 常规多文件 IDE
  return `${baseName}${adapter.fileExt}`;
}

/**
 * 合并多个规则为单文件（用于 Windsurf、Copilot 等）
 */
function mergeRulesForSingleFile(rules, ide) {
  const adapter = getAdapter(ide);
  const sections = rules.map((rule, index) => {
    const separator = index > 0 ? "\n\n---\n\n" : "";
    return separator + rule.content;
  });

  const meta = {
    description: "Project Rules - Generated by ide-rule",
    title: "Project Rules"
  };

  let header = "";
  if (adapter.headerTemplate) {
    header = adapter.headerTemplate(meta);
  }

  return header + sections.join("");
}

module.exports = {
  formatForIde,
  formatBaseRule,
  formatCategoryRule,
  getOutputFileName,
  mergeRulesForSingleFile,
  stripExistingFrontmatter
};

